'use client';
import { useRef } from 'react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { Button } from '@/components/ui/button';

interface PDFExportProps {
  content: string;
  category: string;
}

export default function PDFExport({ content, category }: PDFExportProps) {
  const contentRef = useRef<HTMLDivElement>(null);

  const generatePDF = async () => {
    if (!contentRef.current) return;

    const canvas = await html2canvas(contentRef.current, {
      scale: 2,
      useCORS: true,
      allowTaint: true,
      backgroundColor: '#ffffff',
    });

    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    const imgWidth = 210; // A4 width in mm
    const pageHeight = 295; // A4 height in mm
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    let heightLeft = imgHeight;
    let position = 0;

    // Handle multi-page documents
    while (heightLeft >= 0) {
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
      position -= pageHeight;
      if (heightLeft > 0) pdf.addPage();
    }

    pdf.save(`visa-guidance-${category.replace(/\s+/g, '-').toLowerCase()}-${Date.now()}.pdf`);
  };

  return (
    <>
      <div ref={contentRef} style={{ position: 'absolute', left: '-9999px', top: '-9999px', width: '800px', padding: '20px', background: 'white', color: 'black', fontFamily: 'Arial, sans-serif' }}>
        <h1 style={{ color: '#0891b2', fontSize: '24px', marginBottom: '20px' }}>VisaLens AI Copilot - {category}</h1>
        <div style={{ fontSize: '14px', lineHeight: '1.6' }} dangerouslySetInnerHTML={{ __html: content.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>').replace(/\n/g, '<br>') }} />
        <footer style={{ marginTop: '40px', fontSize: '12px', color: '#666' }}>
          Generated by VisaLens AI on {new Date().toLocaleDateString()} | Powered by Groq Llama-3.3
        </footer>
      </div>
      <Button onClick={generatePDF} className="bg-green-600 hover:bg-green-500 text-white px-4 py-2 rounded-lg">
        📥 Download PDF
      </Button>
    </>
  );
}